print("Hello world")
#print("Hello again")
#print("I like typing this")
#print("This is fun")
#print('Yay! Printing.')
#print("I'd mcuh rather you 'not'")
#print('I "said" do not touch this')
print("HI jonpaul")